language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "pypy"

env:
  - FLASK="==0.8" PUSHER="<1.0"
  - FLASK="==0.8"
  - FLASK="==0.9" PUSHER="<1.0"
  - FLASK="==0.9"
  - FLASK="==0.10.1" PUSHER="<1.0"
  - FLASK="==0.10.1"

matrix:
  include:
    - python: 3.4
    - env: FLASK="==0.10.1"

install:
  - pip install -q Flask$FLASK pusher$PUSHER
  - pip install unittest2 coverage coveralls
  - python setup.py install

script:
  - coverage run --source=flask_pusher setup.py test

after_success:
  - coveralls
