language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"

env:
  - FLASK=0.8
  - FLASK=0.9
  - FLASK=0.10.1

install:
  - pip install -q Flask==$FLASK
  - pip install unittest2 coverage coveralls
  - python setup.py install

script:
  - coverage run --source=flask_pusher setup.py test

after_success:
  - coveralls
