language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"

env:
  - FLASK=0.9
  - FLASK=0.10.1

install:
  - pip install -q Flask==$FLASK
  - pip install unittest2
  - python setup.py install

script:  python tests.py
