language: python

python:
  - "2.6"
  - "2.7"
  - "pypy"

env:
  - FLASK="==0.8" PUSHER="pusher<1.0"
  - FLASK="==0.8"
  - FLASK="==0.9" PUSHER="pusher<1.0"
  - FLASK="==0.9"
  - FLASK="==0.10.1" PUSHER="pusher<1.0"
  - FLASK="==0.10.1"
  - FLASK="==0.10.1" PUSHER="git+https://github.com/pusher/pusher-http-python.git"

matrix:
  include:
    - python: 3.3
      env: FLASK="==0.10.1"
    - python: 3.4
      env: FLASK="==0.10.1"

install:
  - pip install -q Flask$FLASK $PUSHER
  - pip install unittest2 coverage coveralls
  - python setup.py install

script:
  - coverage run --source=flask_pusher setup.py test

after_success:
  - coveralls
